base.url=https://tutorialsninja.com/demo
browser=chrome
# ==========================================
# Valid Login Credentials
valid.email=jetiw79975@jsncos.com
valid.password=12345
# Invalid Login Credentials (for negative tests)
invalid.email=wrong@wrong.com
invalid.password=wrongpass
# Search Terms
search.term=MacBook
search.invalid=xyznotexist999
# Wait Settings (seconds)
implicit.wait=8
explicit.wait=15